### ISSUE TITLE
Verkeerde link op startpagina

### ISSUE THREAD

**Issue by MMJansen** [ed2c/.github#1]
Op https://github.com/ed2c, in het onderdeel Analytics, verwijst de link die heet "Onderliggend package" naar de lokatie van het demo project, en niet naar het package.
Kun je de tekst aanpassen van "Onderliggend package" naar "Package `wisselstroom`, nodig voor de demo",
en de link van "https://github.com/ed2c/wisselstroom_demo" naar "https://github.com/ed2c/wisselstroom" ?
Dank!

**Comment by CorneeldH** [comment]
Hoi, dank voor het doorgeven. Gefixed!

**Comment by CorneeldH** [comment]
done
